name, age, place = input('Hi! What is your name?'), input('Your age')
place = input('Your place?')
print("This is {}".format(name))
print("It is {}".format(age))
print("(S)he live in {}".format(place))